name: sync_note
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  go_router: ^8.0.2
  google_fonts: ^5.0.0
  jiffy: ^6.2.1
  line_icons: ^2.0.1
  logger: ^1.4.0
  lottie: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#CAD4EB"
  color_dark: "#09090F"
  image: images/logo_light.png
  image_dark: images/logo_dark.png

  android_12:
    image: images/logo_light.png
    image_dark: images/logo_dark.png
    color: "#CAD4EB"
    color_dark: "#09090F"
  fullscreen: true

    
    

flutter:
  uses-material-design: true
  assets: 
    - images/
